name: Build release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - src/**
      - "**/*.lua"
      - xmake.lua

permissions:
  contents: read
  actions: write

jobs:
  build-core:
    runs-on: windows-2022
    if: github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.package-build.outputs.version }}
      majorMinorVersion: ${{ steps.package-build.outputs.majorMinorVersion }}

    steps:
      - name: Checkout working repository
        uses: actions/checkout@v4
        with:
          path: MotorTownMods
          fetch-depth: 0 # Allows diff to work

      - name: Check for src changes
        id: check-src-changes
        run: |
          git -C MotorTownMods diff --quiet ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- src/ || echo "src_changed=true" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            .xmake
            Binaries
            Intermediates
            C:/Users/runneradmin/AppData/Local/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}

      - name: Checkout UE4SS
        uses: actions/checkout@v4
        if: steps.check-src-changes.outputs.src_changed == 'true' || hashFiles('Binaries/Game__Shipping__Win64/MotorTownMods/MotorTownMods.dll') == ''
        with:
          repository: drpsyko101/RE-UE4SS
          ref: amc
          path: RE-UE4SS
          submodules: recursive
          token: ${{ secrets.UEPSEUDO_PAT }}

      - name: Prep xmake
        if: steps.check-src-changes.outputs.src_changed == 'true' || hashFiles('Binaries/Game__Shipping__Win64/MotorTownMods/MotorTownMods.dll') == ''
        shell: pwsh
        run: Write-Output "includes(`"RE-UE4SS`")`r`nincludes(`"MotorTownMods`")" | Out-File xmake.lua

      - name: Setup Python
        uses: actions/setup-python@v4
        if: steps.check-src-changes.outputs.src_changed == 'true' || hashFiles('Binaries/Game__Shipping__Win64/MotorTownMods/MotorTownMods.dll') == ''
        with:
          python-version: "3.9"

      # Specifically use MSVC toolset v19.39.33523
      - name: Install VS2022 BuildTools 17.9.7
        if: steps.check-src-changes.outputs.src_changed == 'true' || hashFiles('Binaries/Game__Shipping__Win64/MotorTownMods/MotorTownMods.dll') == ''
        run: choco install -y visualstudio2022buildtools --version=117.9.7.0 --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installChannelUri https://aka.ms/vs/17/release/180911598_-255012421/channel"

      - name: Setup xmake
        if: steps.check-src-changes.outputs.src_changed == 'true' || hashFiles('Binaries/Game__Shipping__Win64/MotorTownMods/MotorTownMods.dll') == ''
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.3"

      - name: Build
        if: steps.check-src-changes.outputs.src_changed == 'true' || hashFiles('Binaries/Game__Shipping__Win64/MotorTownMods/MotorTownMods.dll') == ''
        run: |
          xmake f -m "Game__Shipping__Win64" -y
          xmake project -k vsxmake2022 -m "Game__Shipping__Win64" -y
          xmake build

      - name: Package build
        id: package-build
        shell: pwsh
        run: |
          New-Item -ItemType Directory .\MotorTownMods\dlls
          Copy-Item .\Binaries\Game__Shipping__Win64\MotorTownMods\MotorTownMods.dll .\MotorTownMods\dlls\main.dll
          $staticsFile = Get-Content -Raw .\MotorTownMods\Scripts\Statics.lua
          [regex]$versionRegex = 'ModVersion = "(.*)",'
          $modVersion = $versionRegex.Match($staticsFile).Groups[1].Value
          Compress-Archive -Path .\MotorTownMods ".\MotorTownMods_v${modVersion}.zip"
          Write-Output "version=$modVersion" >> $env:GITHUB_OUTPUT
          [regex]$majorMinorVersionRegex = '^([0-9]+\.[0-9]+)'
          Write-Output "majorMinorVersion=$($majorMinorVersionRegex.Match($modVersion).Groups[1].Value)" >> $env:GITHUB_OUTPUT
          (Get-Content -Path $env:GITHUB_EVENT_PATH | ConvertFrom-Json).head_commit.message > commit_msg.txt
          Get-Content commit_msg.txt | select -skip 2 > release_description.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MotorTownMods_deps_release
          path: |
            MotorTownMods_v*.zip
            release_description.md
          overwrite: true

  build-deps:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: MotorTownMods_deps_lua

      - uses: ilammy/msvc-dev-cmd@v1
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')

      - uses: ilammy/setup-nasm@v1
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')

      - uses: luarocks/gh-actions-lua@v11
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')

      - uses: luarocks/gh-actions-luarocks@v6
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')

      - uses: shogo82148/actions-setup-perl@v1
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')
        with:
          perl-version: "5.32"
          distribution: strawberry

      - name: Checkout OpenSSL
        uses: actions/checkout@v4
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')
        with:
          repository: openssl/openssl
          path: OpenSSL
          ref: openssl-3.0

      - name: Build OpenSSL
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')
        run: |
          cd OpenSSL
          perl Configure VC-WIN64A
          nmake

      - name: install modules
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')
        run: |
          luarocks install --local luasocket
          luarocks install --local luasec OPENSSL_DIR=${{ github.workspace }}\OpenSSL
          luarocks install --local bcrypt

      - name: Package modules
        if: hashFiles('shared.zip') == '' || contains(github.event.pull_request.labels.*.name, 'build-deps')
        shell: pwsh
        run: |
          New-Item -ItemType Directory shared
          Copy-Item -Recurse -Force $env:APPDATA\luarocks\lib\lua\5.4\* .\shared\
          Copy-Item -Recurse -Force $env:APPDATA\luarocks\share\lua\5.4\* .\shared\
          Compress-Archive -Path .\shared ".\shared.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MotorTownMods_deps_lua
          path: shared.zip
          overwrite: true

  create-release:
    if: github.event.pull_request.merged == true
    needs:
      - build-core
      - build-deps
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: MotorTownMods_deps_*
          merge-multiple: true

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        continue-on-error: true
        with:
          token: ${{ github.token }}
          tag: v${{ needs.build-core.outputs.majorMinorVersion }}
          assets: "*"

      - name: Create/update release
        uses: softprops/action-gh-release@v2
        with:
          name: MotorTownMods v${{ needs.build-core.outputs.version }}
          tag_name: v${{ needs.build-core.outputs.majorMinorVersion }}
          body_path: release_description.md
          files: "**/*.zip"
          make_latest: true
